### PR TITLE
Fix Unmounter behaviour and implement Mounter

### LINKED ISSUE #75: Support for fine-grained internal event handling (element creation, re-creation, removal)
Finding vecty pretty interesting, just working through a PoC to get my head around it, and one thing I'm butting up against is trying to integrate with 3rd-party JavaScript that expects to have access to elements in the DOM.  There doesn't currently appear to be any way to know when elements are actually rendered.

We have the `Unmount` handler, which is great for one direction, but what about support for a `Mounted` event?  Or am I missing something and thinking about this all wrong?  I'm sure there are some caveats to doing DOM manipulation outside the framework, as elements may get replaced, etc, but there are times when you really need to get at the rendered element.

### LINKED ISSUE #85: Incorrect Unmounter behavior in certain situations
> I believe the current behaviour for `Unmounter` is incorrect.  In the case where two components return the same HTML tag, the previous component will be replaced without `Unmount` being called.
>
> Only way I can see to produce the correct behaviour here is via reflection.  I've implemented this in 3df8654e9fac557d5707befd718432533ad7e8c3, and I'm now seeing consistent Mount/Unmount behaviour when I'd expect it.

### LINKED ISSUE #135: CustomEvent for when the actual DOM node is created
Hi,

I'm creating this issue because I had a need to get the actual DOM node for one of my components. The use case was:

"When rendering a list of nodes, I want to scroll to the last element on that list".

This is can be done using "domNode.scrollIntoView()".

So, in order to enabled that I changed a few things on "vecty"

on "package event":
```
// DOMCreated is called when the given dom node is created but it might not
// be inserted into the DOM.
//
// Use RAF from withing this handler to ensure your node is present on the document.
func DOMCreated(listener func(ev *vecty.Event)) *vecty.EventListener {
	return &vecty.EventListener{
		Name:     "domcreated",
		Listener: listener,
	}
}

// RAF executes step on the next frame
func RAF(step func()) {
	js.Global.Call("requestAnimationFrame", step)
}
```
on "package vecty" (dom.go)
```
// Incompatible node, start fresh
if prev == nil {
	prev = &HTML{}
}
h.createNode()
defer func() {
	h.new = false

	// fire an event on the dom object
	doc := js.Global.Get("document")
	createEv := doc.Call("createEvent", "HTMLEvents")
	createEv.Call("initEvent", "domcreated", false, true)
	h.node.Call("dispatchEvent", createEv)
}()
```

Then in my component function:
```
func (m *MyComponent) scrollToView(ev *vecty.Event) {
	event.RAF(func() {
		ev.Target.Call("scrollIntoView")
	})
}

func (m *MyComponent) Render() *vecty.HTML {
	return elem.Article(
		event.DOMCreated(m.scrollToView),
		... // other nodes/attributes/etc...
	)
}
```

Using the RAF solution isn't pretty, but given how vecty works I think it'll work all the times and this is also a standard so we can trust that it will be present on the browsers.

I didn't included any polyfill or browser detection but this is just an idea.

There is no branch/fork since I want to know if this is a desired feature and if the implementation is OK.

Thanks in advance.

### PR DESCRIPTION
**Pull request by pdf**
Had a few hours spare tonight, and this has been on my mind, so I took a first pass at it.  I think this is in pretty decent shape if you get a chance to look over it @slimsag.

Fixes #75, fixes #85, fixes #135

### CODE REVIEW

**Comment by pdf** [comment]
At some stage I would like to move the `dom_utils.go` functions to methods on `*HTML`, and integrate these lifecycle events into the DOM manipulation calls, to ensure they're always called as the codebase evolves.  I elected not to do so in this PR though, so as to make the changeset easier to parse.

File: dom.go [hunk 1]
```diff
@@ -52,11 +52,19 @@ type Copier interface {
 	Copy() Component
 }
 
+// Mounter is an optional interface that a Component can implement in order
+// to receive component mount events.
+type Mounter interface {
+	// Mount is called after the component has been mounted, after the DOM node
+	// has been attached.
```
Comment (slimsag) [inline dom.go]: replace `, after the DOM node` with `, i.e. after the DOM node` since we're explaining what it means for a component to be mounted. There isn't an important distinction between a component being mounted and a DOM node being attached.

**Comment by slimsag** [comment]
Sorry I haven't had a chance to look at this fully yet. I should have some time this weekend.

**Comment by pdf** [comment]
No problem.  Was thinking I might start on keyed children next, unless you have thoughts on other priorities?

**Comment by slimsag** [comment]
@pdf sounds good. Any chance you could create issues for the remaining items that were in your original PR (https://github.com/gopherjs/vecty/pull/112/files) that are not yet in master?

Things that are on the top of my head:

- Keyed children rendering - https://github.com/gopherjs/vecty/issues/25
- Optimized rendering using requestAnimationFrame, can just use https://github.com/gopherjs/vecty/issues/79
- batch rendering (I still don't follow the goals/ideas of this so we should discuss on an issue before doing a PR)
- try removing the `nil` -> `noscript` conversion, I created https://github.com/gopherjs/vecty/issues/143

Anything else you remember being in your old PR that has not yet landed in some other form?

**Comment by pdf** [comment]
That's pretty much everything I think.  Batched rendering and the RAF-related code are the same thing, we can discuss later.

A quick review of my old commits did raise one thing that I haven't handled in this PR - unmounted components should be blocked from Rerender, in case an event queues a rerender while we're in the process of tearing down a tree.  I could do this by setting `Core.prevRender` to `nil` in `unmount()`, but that will trigger the panic in Rerender when this case is hit.

We could downgrade the panic to an error/warn log, or track the unmounted state via another field on `Core`.  Preference?

**Comment by slimsag** [comment]
I'd like to keep the panic, so an unmounted state via another field on `Core` sounds good.

File: dom.go [hunk 2]
```diff
@@ -181,7 +185,7 @@ func (h *HTML) reconcile(prev *HTML) {
 			h.node.Set(name, value)
 		}
 	}
-	if !h.new {
+	if h.node == prev.node {
```
Comment (slimsag) [inline dom.go]: For readability sake I'd like to declare this as `new := h.node != prev.node` and continue using `!new` in the if statement. I'll make this change before merging.

Comment (pdf) [reply dom.go]: I'm online currently, happy to edit this in if you'd like.

Comment (slimsag) [reply dom.go]: If you're still online, please do :)

Comment (slimsag) [reply dom.go]: Actually, just cherry-pick my commit onto your branch if you don't mind: https://github.com/gopherjs/vecty/commit/059f8593ecdd7c13ffee79da47ebdaad6448e244

File: dom.go [hunk 3]
```diff
@@ -453,11 +468,18 @@ func Rerender(c Component) {
 	if prevRender == nil {
 		panic("vecty: Rerender invoked on Component that has never been rendered")
 	}
-	nextRender, skip := renderComponent(c, prevRender)
+	if c.Context().unmounted {
+		global.Get("console").Call("warn", "vecty: Rerender invoked on unmounted Component")
```
Comment (slimsag) [inline dom.go]: I'm not sure I like this. I feel semi-strongly that this should either be a panic or non-existent.

In this situation, is the user of Vecty at fault / they made a programming mistake (panic)?

Or is this just something that can occur because of Rerender being incidentally invoked after a component is unmounted in an event handler (silent / no warning)?

File: dom.go (hunk 2 above)
Comment (slimsag) [reply dom.go]: Sorry, please disregard my last two comments and see my comment below instead.

**Comment by slimsag** [comment]
@pdf everything here looks good except my two inline comments. My suggestion would be to use the two commits i've put into this PR: https://github.com/gopherjs/vecty/pull/145

WDYT? If those look good to you, I'll merge this one and then that one.

**Comment by pdf** [comment]
Yeah, I'm fine with merging #145 on top of this.

File: dom.go (hunk 3 above)
Comment (pdf) [reply dom.go]: The user _may_ have made a programming mistake to produce this that they didn't intend, but I think it's most likely to occur due to a race in some evented code that they don't necessarily care about.

**Comment by pdf** [comment]
Feels like things are starting to come together nicely FeelsGoodMan :sunglasses:

**Comment by slimsag** [comment]
😄
